### ISSUE TITLE
error looping through float breakup

### ISSUE THREAD

**Issue by oscarechobravo** [martinaustwick/PythonMapzen#1]
had to cast 'breakup' to int so that loop would work. looping with floats made it sad :)

works after that.

**Comment by oscarechobravo** [comment]
Also, this probably breaks how the chopping of the 50x50 matrices is happening due to some rounding errors - I am yet to investigate. My brute force solution is to cast to int and hope for the best - I can fix when I have more time.

**Comment by martinaustwick** [comment]
What error(s) did it produce? I'm a bit unused to these non-strongly typed paradigms :)

**Comment by oscarechobravo** [comment]
```
TypeError                                 Traceback (most recent call last)
<ipython-input-75-ee21b23ea993> in <module>()
      2 
      3 locations = []
----> 4 for i in range(0, breakup):
      5     locations.append([])
      6 
TypeError: 'float' object cannot be interpreted as an integer
```

Happens in the two code blocks where you deal with the var <code>breakup</code>.

fixed by doing

```for i in range(0, int(breakup)): ``` but this will produce some rounding errors, meaning we might miss data our

**Comment by martinaustwick** [comment]
Huh. I've not had this problem - I have breakup as an int. I wonder what could be causing this? 
![screenshot 2017-06-07 11 39 44](https://user-images.githubusercontent.com/3421932/26874594-243feff2-4b76-11e7-9642-177807d5f7f3.png)

**Comment by martinaustwick** [comment]
Doesn't seem to make any difference in my code if I cast to int either

**Comment by oscarechobravo** [comment]
Probably the flavour of python/ipython we are using. Python 3 in jupyter is me.

**Comment by martinaustwick** [comment]
Hm. Might be using 2.7 myself. What value does breakup take for the demo dataset I emailed you?

**Comment by martinaustwick** [comment]
I've updated the code to explicitly cast that variable to an int, and made print calls which are Python3-friendly - hopefully that should work for everyone, let me know if there are more incompatibilities...
